# Generated by Django 3.1.7 on 2021-08-25 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(max_length=50)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.day')),
            ],
        ),
    ]
