# Generated by Django 3.1.7 on 2021-08-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_ownexercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseinstance',
            name='performance',
            field=models.FileField(blank=True, null=True, upload_to='performaces/'),
        ),
    ]
