# Generated by Django 3.1.7 on 2021-08-26 10:39

from django.db import migrations, models
import fitness.models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0006_auto_20210826_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownexercise',
            name='performance',
            field=models.FileField(blank=True, null=True, upload_to='performaces/'),
        ),
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(default=fitness.models.tomorrow),
        ),
    ]
