# Generated by Django 3.1.7 on 2021-09-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0007_auto_20210826_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weightatdate',
            options={'ordering': ['user', '-date']},
        ),
        migrations.AddField(
            model_name='exerciseinstance',
            name='review',
            field=models.TextField(blank=1, help_text='Enter a review of the performance.', max_length=1000, null=1),
            preserve_default=1,
        ),
    ]
