# Generated by Django 3.1.7 on 2021-09-04 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitness', '0008_auto_20210904_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerrequest',
            name='trainer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
