# Generated by Django 3.1.7 on 2021-09-06 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0011_auto_20210906_0842'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exerciseinstance',
            unique_together={('day', 'exercise')},
        ),
    ]
